default:
  image: rust:slim

build-wasm:
  stage: build
  script:
    - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - wasm-pack build --target web ./tictactoe-rs

build-npm:
  stage: build
  script:
    - apk add npm 
    - npm install
    - npm install ./tictactoe-rs/pkg

pages:
  script:
    - npm run build
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
  
  