[package]
name = "tictactoe-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.83"
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
